# Generated by Django 6.0.4 on 2026-05-03 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0002_subscriptionplan_userpreference_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=4)),
                ('total_cycles', models.PositiveSmallIntegerField(default=10)),
                ('difficulty_tag', models.CharField(blank=True, help_text='e.g. BEGINNER, ADVANCED', max_length=40)),
                ('intensity_level', models.PositiveSmallIntegerField(default=1, help_text='1-4 dots in UI')),
                ('theme_color', models.CharField(blank=True, help_text='teal, pink, …', max_length=20)),
                ('phases', models.JSONField(default=list, help_text='List of {phase, seconds} e.g. inhale/hold/exhale')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='breathingsession',
            name='cycles_completed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='mood_label',
            field=models.CharField(blank=True, choices=[('terrible', 'Terrible'), ('bad', 'Bad'), ('okay', 'Okay'), ('good', 'Good'), ('excellent', 'Excellent')], max_length=20),
        ),
        migrations.AddField(
            model_name='breathingsession',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='wellness.breathingexercise'),
        ),
    ]
