# Generated by Django 6.0.4 on 2026-05-03 19:46

import django.db.models.deletion
import features.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='CBTTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuestQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('mood_logs_used', models.PositiveSmallIntegerField(default=0)),
                ('fear_forecasts_used', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('total_days', models.PositiveSmallIntegerField(default=14)),
                ('free_preview_days', models.PositiveSmallIntegerField(default=3, help_text='Days unlocked without premium; later days require premium.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WorryForecastTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AlterModelOptions(
            name='premiumplan',
            options={'ordering': ['sort_order', 'price']},
        ),
        migrations.AddField(
            model_name='groundingquestsession',
            name='camera_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groundingquestsession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groundingquestsession',
            name='quest_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='groundingquestsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groundingquestsession',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='groundingquestsession',
            name='task_progress',
            field=models.JSONField(default=features.models.default_grounding_quest_tasks),
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='badge_tag',
            field=models.CharField(blank=True, help_text='REGULAR, BEST VALUE, PREMIUM, …', max_length=40),
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='ui_version',
            field=models.CharField(choices=[('old', 'Old layout'), ('new', 'New layout')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='analytics_sharing',
            field=models.CharField(choices=[('private', 'Private'), ('share', 'Share')], default='share', max_length=20),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='demo_reset_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='replay_tutorial_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='selected_program_key',
            field=models.CharField(blank=True, help_text='e.g. quick_start_14, deep_dive_30', max_length=40),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='theme_mode',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='groundingquestsession',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='groundingquestsession',
            name='grounding_type',
            field=models.CharField(default='room-scan', max_length=60),
        ),
        migrations.AlterField(
            model_name='groundingquestsession',
            name='title',
            field=models.CharField(default='Grounding Quest', max_length=120),
        ),
        migrations.CreateModel(
            name='ExposureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('specific_exposure', models.TextField()),
                ('difficulty_level', models.PositiveSmallIntegerField(default=5, help_text='1-10')),
                ('ladder_status', models.CharField(choices=[('not_scheduled', 'Not scheduled'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='not_scheduled', max_length=20)),
                ('check_in_note', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('distress_before', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('distress_after', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposure_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_number', models.PositiveSmallIntegerField()),
                ('label_date', models.CharField(blank=True, help_text='Display-only date label', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('content_body', models.TextField(blank=True)),
                ('action_steps', models.JSONField(default=list)),
                ('journal_prompts', models.JSONField(default=list)),
                ('regulation_tool', models.JSONField(blank=True, default=dict)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='features.programtrack')),
            ],
            options={
                'ordering': ['program', 'day_number'],
                'unique_together': {('program', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='SOSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.CharField(choices=[('select_mode', 'Select mode'), ('breathe', 'Breathe'), ('grounding', 'Grounding'), ('name_it', 'Name it'), ('done', 'Done')], default='select_mode', max_length=20)),
                ('active_mode', models.CharField(blank=True, choices=[('breathe', 'Breathe'), ('grounding', 'Grounding')], max_length=20)),
                ('breathe_cycles_completed', models.PositiveSmallIntegerField(default=0)),
                ('grounding_see', models.TextField(blank=True)),
                ('grounding_hear', models.TextField(blank=True)),
                ('grounding_feel', models.TextField(blank=True)),
                ('fear_statement', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('wants_sos_plus', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FearForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('story_text', models.TextField(help_text="The scary 'what if' narrative")),
                ('category', models.CharField(blank=True, max_length=80)),
                ('belief_strength', models.PositiveSmallIntegerField(default=50, help_text='0-100')),
                ('template_key', models.CharField(blank=True, max_length=80)),
                ('proof_check_in', models.CharField(choices=[('tonight', 'Tonight'), ('tomorrow_morning', 'Tomorrow morning'), ('after_event', 'After the event'), ('none', 'No reminder')], default='none', max_length=30)),
                ('likelihood_percent', models.PositiveSmallIntegerField(default=50)),
                ('distress_level', models.PositiveSmallIntegerField(default=5, help_text='0-10')),
                ('status', models.CharField(choices=[('live', 'Live'), ('expired', 'Expired'), ('resolved', 'Resolved')], default='live', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('safe', 'It was fine / safe'), ('happened', 'It happened')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fear_forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='features_fe_user_id_ddb63a_idx'), models.Index(fields=['device_id', 'status'], name='features_fe_device__8efb23_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserDayCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='features.programday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day')},
            },
        ),
        migrations.CreateModel(
            name='UserProgramProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_opened_day', models.PositiveSmallIntegerField(default=1)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='features.programtrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'program')},
            },
        ),
    ]
