# Generated by Django 6.0.4 on 2026-05-03 20:07

from django.db import migrations, models


def seed_premium_figma_and_paywalls(apps, schema_editor):
    PremiumPlan = apps.get_model("features", "PremiumPlan")
    AppContent = apps.get_model("features", "AppContent")

    md = PremiumPlan.objects.filter(plan_key="monthly-default").first()
    if md:
        PremiumPlan.objects.filter(pk=md.pk).update(
            name="Monthly",
            price="9.99",
            billing_cycle="monthly",
            badge_tag="REGULAR",
            sort_order=0,
            ui_version="new",
            is_legacy=False,
            ios_product_id="com.breakfree.premium.monthly",
            google_product_id="breakfree_premium_monthly",
            feature_summary=(
                "Daily reset tools, guided programs, mood tracking, Forecast proof bank, SOS+ aftercare."
            ),
        )

    PremiumPlan.objects.update_or_create(
        plan_key="yearly-best",
        defaults={
            "name": "Yearly",
            "price": "59.99",
            "billing_cycle": "yearly",
            "badge_tag": "BEST VALUE",
            "sort_order": 1,
            "ui_version": "new",
            "is_legacy": False,
            "is_active": True,
            "ios_product_id": "com.breakfree.premium.yearly",
            "google_product_id": "breakfree_premium_yearly",
            "feature_summary": "Best value yearly access.",
        },
    )
    PremiumPlan.objects.update_or_create(
        plan_key="lifetime-premium",
        defaults={
            "name": "Lifetime",
            "price": "199.00",
            "billing_cycle": "lifetime",
            "badge_tag": "PREMIUM",
            "sort_order": 2,
            "ui_version": "new",
            "is_legacy": False,
            "is_active": True,
            "ios_product_id": "com.breakfree.premium.lifetime",
            "google_product_id": "breakfree_premium_lifetime",
            "feature_summary": "One-time purchase for lifetime premium access.",
        },
    )

    AppContent.objects.update_or_create(
        key="premium_paywall_new",
        defaults={
            "payload": {
                "headline": "Break Free From Anxiety Faster",
                "primary_cta": "Start Your Journey",
                "secondary_cta": "Continue",
                "feature_checklist": [
                    "Daily mental reset tools",
                    "Guided programs and exercises",
                    "AI coach support",
                    "Mood tracking and progress insights",
                    "Personal growth journey tracking",
                ],
                "why_upgrade_intro": "Premium unlocks Day 4+ of your program, deeper SOS aftercare, and weekly insights.",
                "what_you_unlock": [
                    {"title": "SOS+ tools", "body": "Extra grounding + aftercare steps."},
                    {"title": "AI Coach Insights", "body": "Insights from mood, journal, predictions, exposures."},
                    {"title": "Forecast + proof system", "body": "Turn worries into testable predictions."},
                    {"title": "Personal action plans", "body": "Daily and weekly steps."},
                ],
                "preview_lesson_quote": "Your nervous system can learn safety through gentle, repeated practice.",
            },
        },
    )
    AppContent.objects.update_or_create(
        key="premium_paywall_old",
        defaults={
            "payload": {
                "header_title": "Break Free Premium",
                "why_upgrade": (
                    "Unlock Day 4+ of your program, deeper SOS aftercare, and weekly insights."
                ),
                "what_you_unlock": [
                    {"title": "SOS+ tools", "body": "Extra grounding + aftercare steps."},
                    {"title": "AI Coach Insights", "body": "Insights based on mood, journal, forecasts, exposures."},
                    {"title": "Forecast + proof system", "body": "Build evidence against anxious thoughts."},
                    {"title": "Personal action plans", "body": "Daily and weekly steps."},
                ],
                "cta_sign_in": "Sign In To View Plans",
                "cta_restore": "Restore Purchases",
            },
        },
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_seed_default_premium_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumplan',
            name='google_product_id',
            field=models.CharField(blank=True, help_text='Google Play base plan / product id', max_length=120),
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='ios_product_id',
            field=models.CharField(blank=True, help_text='App Store subscription product id', max_length=120),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='restored_at',
            field=models.DateTimeField(blank=True, help_text='Set when activated via restore-purchase.', null=True),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='store_platform',
            field=models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='store_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Opaque transaction / order id from the store client.', max_length=255),
        ),
        migrations.RunPython(seed_premium_figma_and_paywalls, noop),
    ]
