# Generated by Django 6.0.4 on 2026-04-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_seed_onboarding_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeyprogram',
            name='journey_badge',
            field=models.CharField(blank=True, help_text='e.g. “14 DAYS OF GENTLE GROWTH” — upper line on the program card', max_length=120),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='frequency_badge',
            field=models.CharField(blank=True, help_text='e.g. RARE, OCCASIONAL — shown before the name like “RARE: Quiet Peaks”', max_length=32),
        ),
    ]
